services:
  frontend:
    image: ${REGISTRY}/${GITHUB_REPOSITORY}/frontend:${DOCKER_TAG}
    container_name: ${STACK_NAME}-frontend
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.constraint-label=traefik-public
      - traefik.http.services.${STACK_NAME}-frontend.loadbalancer.server.port=80
      - traefik.http.routers.${STACK_NAME}-frontend-http.rule=Host(`cpe-courses.${DOMAIN}`)
      - traefik.http.routers.${STACK_NAME}-frontend-http.entrypoints=http
      - traefik.http.routers.${STACK_NAME}-frontend-http.middlewares=https-redirect
      - traefik.http.routers.${STACK_NAME}-frontend-https.rule=Host(`cpe-courses.${DOMAIN}`)
      - traefik.http.routers.${STACK_NAME}-frontend-https.entrypoints=https
      - traefik.http.routers.${STACK_NAME}-frontend-https.tls=true
      - traefik.http.routers.${STACK_NAME}-frontend-https.tls.certresolver=le
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
